### ISSUE TITLE
Chrome extension script included in LoAF entry

### ISSUE THREAD

**Issue by rviscomi** [w3c/long-animation-frames#18]
I noticed a Chrome extension `sourceURL` included in a LoAF entry while debugging something locally. There's a related discussion in #10 to expose some info when extensions are slow, but AFAIK the expected behavior now is for extensions to be omitted entirely from LoAF entries, so this may be a regression.

Found with Chrome 127.0.6533.89

```json
{
    "name": "script",
    "entryType": "script",
    "startTime": 3166.699999988079,
    "duration": 7,
    "navigationId": "96287487-2a53-4e97-985d-9d2358949c37",
    "invoker": "DOMWindow.onmessage",
    "invokerType": "event-listener",
    "windowAttribution": "self",
    "executionStart": 3166.699999988079,
    "forcedStyleAndLayoutDuration": 0,
    "pauseDuration": 0,
    "sourceURL": "chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/js/dom.js",
    "sourceFunctionName": "onMessage",
    "sourceCharPosition": 72
}
```

**Comment by mmocny** [comment]
Might want to file a crbug instead?

**Comment by rviscomi** [comment]
Yeah true, not a spec bug

**Comment by rviscomi** [comment]
Reopened https://issues.chromium.org/40275918
